services:
  postgres:
    image: postgres:latest
    container_name: test_postgres
    volumes:
      - test_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB?error}
      POSTGRES_USER: ${POSTGRES_USER?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?error}
      
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h localhost"]
      interval: 5s
      retries: 5
      start_period: 10s
  
volumes:
  test_data: