[tool.ruff]
exclude = ["app/tests/", "app/alembic/", ".env"]
line-length = 79  

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501", "F401"]

[tool.pytest.ini_options]
addopts = "-ra"
markers = [
    "books: all book endpoint tests",
    "reviews: all review endpoint tests",
]